//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За нас.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyGuide е Вашият помощник в намирането на оптималния маршрут през избрани от Вас дестинации.
        ///Използвайте нашата &lt;a href=&quot;/MyGuide/Map/ShowMap&quot;&gt;Карта&lt;/a&gt; за да разгледате, или
        ///директно пробвайте нашето &lt;a href=&quot;/MyGuide/Plan&quot;&gt;търсене&lt;/a&gt; за да съставите Вашия маршрут!
        ///&lt;br&gt;
        ///Ако пък вече сте съставили маршрута си, посетете страницата за &lt;a href=&quot;/MyGuide/Routing/Preview&quot;&gt;преглед на маршрути&lt;/a&gt;!.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string CategoryLabel {
            get {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Изберете ---.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изберете дата.
        /// </summary>
        public static string ChooseDate {
            get {
                return ResourceManager.GetString("ChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Списък с избрани дестинации.
        /// </summary>
        public static string ChosenItems {
            get {
                return ResourceManager.GetString("ChosenItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакти.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изследвайте!.
        /// </summary>
        public static string ExploreLabel {
            get {
                return ResourceManager.GetString("ExploreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ако никога не сте сигурни какво търсите, докато не го видите - не се колебайте да разгледате нашата интерактивна карта! .
        /// </summary>
        public static string ExploreTileContent {
            get {
                return ResourceManager.GetString("ExploreTileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напред.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyGuide - Начало.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тръгване от:.
        /// </summary>
        public static string HomePlaceLabel {
            get {
                return ResourceManager.GetString("HomePlaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некоректен потребител и/или парола.
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключови думи.
        /// </summary>
        public static string KeywordsLabel {
            get {
                return ResourceManager.GetString("KeywordsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Научете повече.
        /// </summary>
        public static string LearnMoreLabel {
            get {
                return ResourceManager.GetString("LearnMoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изход.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ако се изгубите, натиснете тук =&gt; .
        /// </summary>
        public static string LostMessage {
            get {
                return ResourceManager.GetString("LostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Още изображения.
        /// </summary>
        public static string MorePics {
            get {
                return ResourceManager.GetString("MorePics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашият гид към мечтаното пътуване.
        /// </summary>
        public static string MotoLabel {
            get {
                return ResourceManager.GetString("MotoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо е да изберете място на тръгване.
        /// </summary>
        public static string MustChooseStartPoint {
            get {
                return ResourceManager.GetString("MustChooseStartPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все още нямате изчислени маршрути за преглед!.
        /// </summary>
        public static string NoRoutesYet {
            get {
                return ResourceManager.GetString("NoRoutesYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Населено място.
        /// </summary>
        public static string PlaceLabel {
            get {
                return ResourceManager.GetString("PlaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планирайте своето пътешествие.
        /// </summary>
        public static string PlanTourLabel {
            get {
                return ResourceManager.GetString("PlanTourLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Използвайте нашата мощна търсачка, която ще Ви предложи идеалните дестинации за Вашето мечтано пътешествие! След това се доверете на умния маршрутизатор, който ще ги подреди в оптимален ред!.
        /// </summary>
        public static string PlanTourTileContent {
            get {
                return ResourceManager.GetString("PlanTourTileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Популярност.
        /// </summary>
        public static string Popularity {
            get {
                return ResourceManager.GetString("Popularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преглед на маршрут.
        /// </summary>
        public static string PreviewRouteLabel {
            get {
                return ResourceManager.GetString("PreviewRouteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вече изчислихте Вашия маршрут? Идеално! Само трябва да влезете в профила си, след което да последвате бутона &quot;Напред&quot;!.
        /// </summary>
        public static string PreviewTileContent {
            get {
                return ResourceManager.GetString("PreviewTileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето {0} е задължително!.
        /// </summary>
        public static string PropertyValueRequired {
            get {
                return ResourceManager.GetString("PropertyValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премахни.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резултати.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маршрут.
        /// </summary>
        public static string Route {
            get {
                return ResourceManager.GetString("Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запиши маршрут.
        /// </summary>
        public static string SaveRoute {
            get {
                return ResourceManager.GetString("SaveRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търси.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разгледай.
        /// </summary>
        public static string TakeALook {
            get {
                return ResourceManager.GetString("TakeALook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Към картата!.
        /// </summary>
        public static string ToMap {
            get {
                return ResourceManager.GetString("ToMap", resourceCulture);
            }
        }
    }
}
